// Auto-balancer: plays every ball against every other ball headlessly and nudges each
// ball's damage multiplier toward a 50% win rate. Writes js/balance.js.
// node tools/balance.js [iterations]
global.window = globalThis;
for (const f of ['core', 'data', 'data2', 'abilities', 'sim']) require('../js/' + f + '.js');
const fs = require('fs');
const BB = globalThis.BB;
BB.BALANCE = {};
const ids = BB.ITEMS.filter((i) => i.id !== 'dummy' && i.rarity !== 'iridescent').map((i) => i.id);
const SETTINGS = { hitlag: true, parrylag: true, dmgNumbers: false };
function duel(a, b, seed) {
  const s = new BB.Sim({ seed, map: 'classic', settings: SETTINGS, teams: [[{ id: a, hp: 100, slot: 0 }], [{ id: b, hp: 100, slot: 1 }]] });
  while (!s.over && s.t < 150) { s.step(1 / 60); s.events.length = 0; s.fx.length = 0; }
  return s.over ? s.over.winner : -1;
}
const iters = +process.argv[2] || 4;
for (let it = 0; it < iters; it++) {
  const wins = {}, games = {};
  for (const id of ids) { wins[id] = 0; games[id] = 0; }
  for (let i = 0; i < ids.length; i++) for (let j = i + 1; j < ids.length; j++) {
    for (const seed of [11 + it, 101 + it]) {
      const w = duel(ids[i], ids[j], seed * (i + 3) + j);
      games[ids[i]]++; games[ids[j]]++;
      if (w === 0) wins[ids[i]]++; else if (w === 1) wins[ids[j]]++; else { wins[ids[i]] += 0.5; wins[ids[j]] += 0.5; }
    }
  }
  let spread = 0;
  for (const id of ids) {
    const wr = wins[id] / games[id];
    spread = Math.max(spread, Math.abs(wr - 0.5));
    const cur = BB.BALANCE[id] || 1;
    BB.BALANCE[id] = Math.round(Math.min(3.2, Math.max(0.4, cur * Math.pow(0.5 / Math.max(0.05, Math.min(0.95, wr)), 0.6))) * 100) / 100;
  }
  const rows = ids.map((id) => [id, (wins[id] / games[id]).toFixed(2)]).sort((x, y) => y[1] - x[1]);
  console.log('iter', it, 'max deviation', spread.toFixed(2), 'top', rows.slice(0, 3).join(' '), 'bottom', rows.slice(-3).join(' '));
}
const out = '// Generated by tools/balance.js: per-ball damage multipliers tuned toward a 50% duel win rate.\nwindow.BB.BALANCE = ' + JSON.stringify(BB.BALANCE, null, 0).replace(/,/g, ', ') + ';\n';
fs.writeFileSync(__dirname + '/../js/balance.js', out);
console.log('wrote js/balance.js');
